package chap15.chap15_4.chap15_4_6;

public enum Watercolor_2 {
    /*ZINC,LEMON_YELLOW,MEDIUM_YELLOW,DEEP_YELLOW,ORANGE,
    BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,
    CERULEAN_BLUE_HUE,PHTHALO_BLUE,ULTRAMARINE,
    COBALT_BLUE_HUE,PERMANENT_GREEN,VIRIDIAN_HUE,
    SAP_GREEN,YELLOW_OCHER,BURNT_SIENNA,RAW_UMBER,
    BURNT_UMBER,PAYNES_GRAY,IVORY_BLACK*/

    A, B ,C,D,E,F,G,H,I

}
